#!/usr/bin/env bash
# Runs a check against all nginx conf files
# to ensure they are valid

echo "setting keycloak https"
sed -i 's=http://keycloak-8443=https://keycloak-8443=g' /home/dokku/keycloak/nginx.conf

